### ISSUE TITLE
Spelling and Grammar Issues on Week 2

### ISSUE THREAD

**Issue by guti21js** [hunter-college-ossd-spr19/mxmsunny-weekly#1]
In the following recommendations I am referring to week 2's blog post:
https://hunter-college-ossd-spr19.github.io/mxmsunny-weekly/week02/

There are  two errors in the sentence after the second paragraph. 
The sentence "People don’t need to be an expert at coding." uses 'an expert' when talking about a plural subject so it should be changed to 'experts'. Therefore the sentence would be "People don’t need to be experts at coding." 

In the following sentence the word "skillsets" is used but it is supposed to be two separate words "skill sets".

In the third paragraph in the first sentence the word " contributions " should be "contributions". In the end it should say "should be my first contribution".

**Comment by mxmsunny** [comment]
Thank you for your recommendation and pointing these out to me! I have made proper changes to the blogpost.
